# In this practice I will examine the Performance of each Kernel in SVM

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
bank_data = pd.read_csv('/Users/haitonghuang/Downloads/datasets/bill_authentication.csv')
bank_data.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
bank_data.Class.value_counts()

0    762
1    610
Name: Class, dtype: int64

In [4]:
bank_data.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
bank_data[['Variance','Skewness','Curtosis','Entropy']] = scaler.fit_transform(bank_data[['Variance','Skewness','Curtosis','Entropy']])

In [6]:
bank_data

Variance  Skewness  Curtosis   Entropy  Class
0     1.121806  1.149455 -0.975970  0.354561      0
1     1.447066  1.064453 -0.895036 -0.128767      0
2     1.207810 -0.777352  0.122218  0.618073      0
3     1.063742  1.295478 -1.255397 -1.144029      0
4    -0.036772 -1.087038  0.736730  0.096587      0
...        ...       ...       ...       ...    ...
1367 -0.009711 -0.097693 -0.660962  0.300996      1
1368 -0.641313 -1.158984  1.179023  0.730127      1
1369 -1.472357 -2.621646  3.759017 -0.754884      1
1370 -1.406693 -1.756471  2.552043 -0.043158      1
1371 -1.047122 -0.439822  0.298616  1.136464      1

[1372 rows x 5 columns]

In [7]:
x = bank_data.drop(columns = 'Class')
y = bank_data['Class']

In [8]:
print(x,y)

      Variance  Skewness  Curtosis   Entropy
0     1.121806  1.149455 -0.975970  0.354561
1     1.447066  1.064453 -0.895036 -0.128767
2     1.207810 -0.777352  0.122218  0.618073
3     1.063742  1.295478 -1.255397 -1.144029
4    -0.036772 -1.087038  0.736730  0.096587
...        ...       ...       ...       ...
1367 -0.009711 -0.097693 -0.660962  0.300996
1368 -0.641313 -1.158984  1.179023  0.730127
1369 -1.472357 -2.621646  3.759017 -0.754884
1370 -1.406693 -1.756471  2.552043 -0.043158
1371 -1.047122 -0.439822  0.298616  1.136464

[1372 rows x 4 columns] 0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64


In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 2)

In [14]:
#kernel = Linear Kernel
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)

SVC(kernel='linear')

In [15]:
y_pred = svclassifier.predict(x_test)

In [16]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[208   9]
 [  0 195]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       217
           1       0.96      1.00      0.98       195

    accuracy                           0.98       412
   macro avg       0.98      0.98      0.98       412
weighted avg       0.98      0.98      0.98       412



### we are getting 98% accuracy on this model using linear kernel which is very good, but now I will try using a different kernel and let's see if the accuracy will change.

In [18]:
#kernel = Polynomial Kernel
from sklearn.svm import SVC
svclassifier_poly = SVC(kernel='poly', degree=5)
svclassifier_poly.fit(x_train, y_train)

SVC(degree=5, kernel='poly')

In [19]:
y_pred_poly = svclassifier_poly.predict(x_test)

In [20]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred_poly))

[[208   9]
 [  0 195]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88       217
           1       1.00      0.71      0.83       195

    accuracy                           0.86       412
   macro avg       0.90      0.85      0.86       412
weighted avg       0.89      0.86      0.86       412



In [21]:
# Gaussian Kernel
svclassifier_rbf = SVC(kernel='rbf')
svclassifier_rbf.fit(x_train, y_train)

SVC()

In [22]:
y_pred_rbf = svclassifier_rbf.predict(x_test)

In [23]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred_rbf))

[[208   9]
 [  0 195]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       217
           1       1.00      1.00      1.00       195

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412



In [25]:
# Sigmoid Kernel
svclassifier_sig = SVC(kernel='sigmoid')
svclassifier_sig.fit(x_train, y_train)
y_pred_sig = svclassifier_sig.predict(x_test)

In [26]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred_sig))

[[208   9]
 [  0 195]]
              precision    recall  f1-score   support

           0       0.79      0.75      0.77       217
           1       0.73      0.78      0.76       195

    accuracy                           0.76       412
   macro avg       0.76      0.76      0.76       412
weighted avg       0.76      0.76      0.76       412



## Comparison of Kernel Performance
### If we compare the performance of the different types of kernels we can clearly see that the sigmoid kernel performs the worst. This is due to the reason that sigmoid function returns two values, 0 and 1, it is more suitable for binary classification problems.
### Linear Kernel can perform very good with linear data. 
### Also we can see that Gaussian kernel achieved a perfect 100% prediction rate. Gaussian kernel is usually chosen for non-linear data since it's infinit demension characteristic and it is one of the most preferred and used kernel functions in svm

